create tinfoil command
nh-server/Kurisu pull request #1131
Opened 2022-10-17 18:45 UTC by chrisp1v

This creates a tinfoil command

2022-10-17 18:51 UTC, lifehackerhansol requested changes

2022-10-17 18:51 UTC, lifehackerhansol commented on cogs/assistance-cmds/tinfoil.switch.md
> +# We don't recommend the usage of tinfoil for the following reason:
Use bold instead of headers
```suggestion
**We don't recommend the usage of tinfoil for the following reasons:**
```

2022-10-17 18:54 UTC, lifehackerhansol requested changes

2022-10-17 18:54 UTC, lifehackerhansol commented on cogs/assistance-cmds/tinfoil.switch.md
> +**We don't recommend the usage of tinfoil for the following reason:**
Nitpick typo, you have more than one reason so it should be in plural "following reasons"

2022-10-17 18:56 UTC, lifehackerhansol requested changes

2022-10-17 18:56 UTC, lifehackerhansol commented on cogs/assistance-cmds/tinfoil.switch.md
> +- It installs itself to the home menu (instant ban if you connect to nintendo servers).
Capitalize "Nintendo"

2022-10-17 18:56 UTC, lifehackerhansol commented on cogs/assistance-cmds/tinfoil.switch.md
> +title: Why you shouldn't use tinfoil
Capitalize Tinfoil, it is a proper noun

Fix this in every other instance of Tinfoil

2022-10-17 19:23 UTC, lifehackerhansol approved these changes

2024-06-30 04:12 UTC, eip618 commented
got too many downvotes and we don't want negative karma points

2024-06-30 04:12 UTC, closed without merging