Add more commands and fix things
nh-server/Kurisu pull request #1250
Opened 2023-11-26 07:08 UTC by VannyBuns

2023-11-26 20:04 UTC, lifehackerhansol requested changes

2023-11-26 20:04 UTC, lifehackerhansol commented on cogs/assistance-cmds/baninfo.wiiu.md
> +help-desc: Links to ban information pages
it doesn't link to anything

2023-11-26 20:04 UTC, lifehackerhansol commented on cogs/assistance-cmds/cfwuses.wiiu.md
> +# See [here](https://wiki.hacks.guide/wiki/Wii_U:Things_to_do) for a better list.
I don't think this breaks anything but it's probably a good idea to add a newline before this `#`

2023-11-26 20:04 UTC, lifehackerhansol commented on cogs/assistance-cmds/uninstallcfw.wiiu.md
> +https://wiiu.hacks.guide/#/uninstall-payloadloader
This file needs to be written like this command here, since it's just a link https://github.com/nh-server/Kurisu/blob/main/cogs/assistance-cmds/android.switch.md?plain=1

2023-11-26 20:07 UTC, VannyBuns commented on cogs/assistance-cmds/baninfo.wiiu.md
> +help-desc: Links to ban information pages
You're right, I was just following the format of the 3DS and switch descriptions. I'll fix

2023-11-26 20:13 UTC, VannyBuns commented on cogs/assistance-cmds/cfwuses.wiiu.md
> +# See [here](https://wiki.hacks.guide/wiki/Wii_U:Things_to_do) for a better list.
Done

2023-11-26 20:28 UTC, VannyBuns commented on cogs/assistance-cmds/uninstallcfw.wiiu.md
> +https://wiiu.hacks.guide/#/uninstall-payloadloader
Should look good now

2023-11-27 04:08 UTC, lifehackerhansol approved these changes

2023-11-27 04:34 UTC, merged