new alias for command
nh-server/Kurisu pull request #1334
Opened 2024-07-29 09:07 UTC by shinobijolteon

new alias for .transfersave for 3ds

2024-08-01 02:15 UTC, lifehackerhansol requested changes
Not 100% sure if we want yet another alias but meh

2024-08-01 02:15 UTC, lifehackerhansol commented on cogs/assistance-cmds/transfersave.3ds.md
> +aliases: ctdtransfer, ctdsave, savetransfer,
trailing comma

2024-09-28 21:25 UTC, irowiki commented on cogs/assistance-cmds/twl.3ds.md
> -url: https://wiki.hacks.guide/wiki/3DS:TWLFix](https://wiki.hacks.guide/wiki/3DS:DS_mode_unbrick#Section_IV,_Part_I_-_Regular_TWLFix
the TWLfix command is now pointing to the DSU page so this in specific is not needed

2024-09-29 08:07 UTC, lifehackerhansol commented
I'm closing this PR because it's kind of a mess; please actually respond to review comments, and also make unrelated changes in a separate PR.

2024-09-29 08:07 UTC, closed without merging