Create the “Piracy” command
nh-server/Kurisu pull request #864
Opened 2020-12-03 14:29 UTC by 2tmb2

2020-12-03 14:37 UTC, 2tmb2 commented
Wasn’t sure what to do for the thumbnail so I used one that was previously used. That is probably going to change and should probably change, I just wasn’t sure how to change It or what to change it to.

2020-12-03 15:13 UTC, bleck9999 requested changes

2020-12-03 15:13 UTC, bleck9999 commented on cogs/assistance.py
> +        embed.set_author(Name="eip", url = "https://3ds.eiphax.tech/piracy")
Name should be all lowercase

2020-12-03 15:13 UTC, bleck9999 commented on cogs/assistance.py
> +        embed.set__thumbnail(url="https://nintendohomebrew.com/pics/nhplai.png")
Should have only one underscore

2020-12-04 17:40 UTC, 2tmb2 commented on cogs/assistance.py
> +        embed.set_author(Name="eip", url = "https://3ds.eiphax.tech/piracy")
Fixed

2020-12-04 17:40 UTC, 2tmb2 commented on cogs/assistance.py
> +        embed.set__thumbnail(url="https://nintendohomebrew.com/pics/nhplai.png")
Fixed

2021-02-20 05:32 UTC, pbanj commented
glazy told me to

2021-02-20 05:32 UTC, closed without merging

2021-02-20 05:34 UTC, GlaZedBelmont commented
to be accurate, we made an alternative that was merged in https://github.com/nh-server/Kurisu/commit/a3c9881dd3af324520ee7fe6e51c1fedf0c9a624