fixes dsi dump godmode9i
nh-server/Kurisu pull request #965
Opened 2021-06-24 17:41 UTC by quadsYT

The old link doesnt work anymore, so im updating it to fix it
Couldnt test, have bad internet so cant download docker + it just changes the link

2021-06-24 17:55 UTC, lifehackerhansol requested changes
Works, partially. See review

2021-06-24 17:55 UTC, lifehackerhansol commented on cogs/assistance.py
>              embed.url = "https://dsi.cfw.guide/dumping-cartridges"
This still leads to the old link.

2021-06-26 20:57 UTC, quadsYT commented on cogs/assistance.py
>              embed.url = "https://dsi.cfw.guide/dumping-cartridges"
fixed it

2021-06-26 21:58 UTC, lifehackerhansol approved these changes
Works.

2021-06-27 00:07 UTC, merged